### ISSUE TITLE
kernel 4.3 brings a new issue

### ISSUE THREAD

**Issue by donahue95** [fernando-rodriguez/portage-overlay#1]
/var/tmp/portage/x11-drivers/ati-drivers-15.7-r1/work/common/lib/modules/fglrx/build_mod/2.6.x/firegl_public.c: In function ‘firegl_major_proc_read’:
/var/tmp/portage/x11-drivers/ati-drivers-15.7-r1/work/common/lib/modules/fglrx/build_mod/2.6.x/firegl_public.c:653:9: error: void value not ignored as it ought to be
     len = seq_printf(m, "%d\n", major);
         ^
scripts/Makefile.build:258: recipe for target '/var/tmp/portage/x11-drivers/ati-drivers-15.7-r1/work/common/lib/modules/fglrx/build_mod/2.6.x/firegl_public.o' failed

**Comment by fernando-rodriguez** [comment]
I added a patch for that.
